services:
  - type: web
    name: gsm-shop
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: JEPFX
      - key: ADMIN_PASS
        value: JEPFXADMIN
      - key: PORT
        value: 3000
